### ISSUE TITLE
linting doesn report the same errors as local run

### ISSUE THREAD

**Issue by ArthurFlag** [xuorig/redocly-cli-lint-action#235]
Hi and thanks for this action! 

I noticed that my linting action always passing, and my local run of redoc is failing. I'm not sure why that is and how to help diagnose this but here goes:

### Worklow file

```yaml
name: "Lint OpenAPI"

on:
  push:
    paths:
      - 'talon-integration.yml'

jobs:
  lint-open-api:
    name: Lint OpenAPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Run Redocly Lint
      - uses: xuorig/redocly-cli-lint-action@v0.0.1
        with:
          entrypoints: 'talon-integration.yml'
          config: '.redocly.yaml'
```

```
Run xuorig/redocly-cli-lint-action@v0.0.1
  with:
    entrypoints: integration.yml
    config: .redocly.yaml
    format: codeframe
    max_problems: 100
validating integration.yml...
integration.yml: validated in 262ms
Woohoo! Your OpenAPI definition is valid. 🎉
```

`.redocly.yaml`
```yaml
lint:
  extends:
    # - recommended
    - all
    # https://github.com/Redocly/redocly-cli/blob/master/packages/core/src/config/all.ts

  rules:
    request-mime-type: off
    path-segment-plural: off
    paths-kebab-case: off
    info-contact: off
    no-invalid-media-type-examples: off
    operation-description: error
    parameter-description: error
    operation-tag-defined: error
    operation-singular-tag: error
    tag-description: error
    tags-alphabetical: error
    no-identical-paths: error
    boolean-parameter-prefixes:
      severity: off
      prefixes: ['should', 'is', 'has']
    no-unused-components:
      severity: error
    info-license: off
```

### Local run

```bash
npx @redocly/cli lint talon-integration.yml
Error was generated by the scalar-property-missing-example rule.
❌ Validation failed with 1 error.
```

Any idea why the action doesn't fail? Thanks!
